{% set name = "sklearn-compat" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1a0c3a2f384100e034def49ee5a6cfe984a826f79d032eb559f10445e012b02c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True # [py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - scikit-learn >=1.2,<1.9

test:
  imports:
    - sklearn_compat
    - sklearn_compat.utils
  source_files:
    - tests/
  commands:
    - pip check
    - pytest -v tests/
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sklearn-compat/sklearn-compat
  summary: Ease multi-version support for scikit-learn compatible library
  description: |
    This package provides a set of utilities to make scikit-learn estimators
    compatible with different versions of scikit-learn.
  dev_url: https://github.com/sklearn-compat/sklearn-compat
  doc_url: https://sklearn-compat.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - glemaitre
    - adrinjalali
