{% set name = "sklearn-compat" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sklearn_compat-{{ version }}.tar.gz
  sha256: 74f8267613249d599aa3a2f2503af32fa51bce0800b1b0b0a57b52354402454e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True # [py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - scikit-learn >=1.2,<1.7

test:
  imports:
    - sklearn_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sklearn-compat/sklearn-compat
  summary: Ease support for compatible scikit-learn estimators across versions
  description: |
    This package provides a set of utilities to make scikit-learn estimators
    compatible with different versions of scikit-learn.
  dev_url: https://github.com/sklearn-compat/sklearn-compat
  doc_url: https://sklearn-compat.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - glemaitre
    - adrinjalali
